openapi: 3.1.0
info:
  version: 1.0.0
  title: TaskPro app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of TaskPro app

tags:
  - name: Authentication
    description: Operations related to authentication
  - name: Boards
    description: Operations related to boards
  - name: Columns
    description: Operations related to columns
  - name: Tasks
    description: Operations related to tasks
  - name: Email
    description: Operations related to email
servers:
  - url: https://taskpro-backend-qxl7.onrender.com
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
